package es.uva.eii.ds.empresa7.interfaz.pares_vista_control.attcliente;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author franc
 */
public class VistaAtencionCliente extends javax.swing.JFrame {

    private CtrlVistaAtencionCliente control;
    /**
     * Creates new form VistaAtencionCliente
     * @throws CloneNotSupportedException si se intenta clonar una clase que no tenga implementado cloneable
     */
    public VistaAtencionCliente() throws CloneNotSupportedException {
        this.control = new CtrlVistaAtencionCliente(this);
        initComponents();
        this.setFont(new Font("Tahoma", Font.BOLD, 14));
        configuraPantalla();
        
        String nombre=control.procesaEventoPedirNombre();
        int p=control.procesaEventoPedirNumeroPunto();
        muestraBienvenida(nombre,p);
        confirmarDevolucion.setEnabled(false);
        botonNoIncidencias.setEnabled(false);
        botonSiIncidencias.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        puntoAC = new javax.swing.JLabel();
        idReserva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        introducirReserva = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        confirmacion_o_incidencias = new javax.swing.JLabel();
        confirmarDevolucion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosVehiculoYCliente = new javax.swing.JTextArea();
        botonNoIncidencias = new javax.swing.JButton();
        botonSiIncidencias = new javax.swing.JButton();
        numeroPunto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(670, 490));

        puntoAC.setText("Punto:");

        jLabel1.setText("Introduzca el id de la reserva:");

        introducirReserva.setText("Introducir reserva");
        introducirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirReservaActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        confirmarDevolucion.setText("Confirmar devolucion");
        confirmarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarDevolucionActionPerformed(evt);
            }
        });

        datosVehiculoYCliente.setEditable(false);
        datosVehiculoYCliente.setColumns(20);
        datosVehiculoYCliente.setRows(5);
        jScrollPane2.setViewportView(datosVehiculoYCliente);

        botonNoIncidencias.setText("No incidencias");
        botonNoIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoIncidenciasActionPerformed(evt);
            }
        });

        botonSiIncidencias.setText("Si incidencias");
        botonSiIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiIncidenciasActionPerformed(evt);
            }
        });

        numeroPunto.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntoAC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonNoIncidencias)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                                        .addComponent(botonSiIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmacion_o_incidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(confirmarDevolucion)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(introducirReserva)))))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numeroPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puntoAC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introducirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmacion_o_incidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiIncidencias)
                    .addComponent(botonNoIncidencias))
                .addGap(29, 29, 29)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introducirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirReservaActionPerformed

            control.procesaEventoAlquiler();
    }//GEN-LAST:event_introducirReservaActionPerformed

    private void confirmarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDevolucionActionPerformed
        try { 
            control.procesaEventoDevolucion();
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(VistaAtencionCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        introducirReserva.setEnabled(false);
        muestraRetroalimentacion(2);
    }//GEN-LAST:event_confirmarDevolucionActionPerformed

    private void botonNoIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoIncidenciasActionPerformed
        try {
            control.finalizaReserva();
            botonSiIncidencias.setEnabled(false);
            confirmarDevolucion.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(VistaAtencionCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(VistaAtencionCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        muestraRetroalimentacion(3);
    }//GEN-LAST:event_botonNoIncidenciasActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        control.procesaEventoGeneraVistaIdentificarse();
    }//GEN-LAST:event_cancelarActionPerformed

    private void botonSiIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiIncidenciasActionPerformed
        control.procesaEventoGeneraVistaIncidencias();
    }//GEN-LAST:event_botonSiIncidenciasActionPerformed

    private void muestraBienvenida(String nombre,int punto){
        bienvenida.setText("Bienvenido empleado de A.cliente, " + nombre + ".");
        numeroPunto.setText("" + punto);
    }

    /**
     * Metodo que coge el id de Reserva
     * @return devuelve el String con el id
     */
    public String getId(){
        return idReserva.getText();
    }

    /**
     * Recibe los datos de la reserva y del cliente y los muestra en la vista de Atencion al Cliente
     * @param matricula del vehiculo
     * @param dni del cliente
     * @param numero numero de cliente
     */
    public void muestraDatos(String matricula, String dni,int numero){
        datosVehiculoYCliente.setText("Matricula del vehiculo: " + "\r\n" + matricula + "\r\n" + "Dni del cliente: " + "\r\n" + dni+ "\r\n" + "Numero De Cliente: "+numero);
        muestraRetroalimentacion(1);
    }
    
    /**
     * Maetodo nque segun el valor de caso dado muestra una inbformacion determinada al usuario
     * @param caso del momento del caso de uso en el que nos encontremos
     */
    public void muestraRetroalimentacion(int caso){
        if(caso == 1){
            confirmacion_o_incidencias.setText("Confirme la devolucion.");
            confirmarDevolucion.setEnabled(true); 
        }
        if(caso == 2){
            confirmacion_o_incidencias.setText("¿Se ha producido alguna incidencia?");
            confirmarDevolucion.setVisible(false);
            botonNoIncidencias.setEnabled(true);
            botonSiIncidencias.setEnabled(true);
        }
        if(caso == 3){
            confirmacion_o_incidencias.setText("Vehiculo situado en punto de entrega.");
            confirmarDevolucion.setEnabled(false);
            botonNoIncidencias.setEnabled(false);
            datosVehiculoYCliente.setText("");
        }
    }
    private void configuraPantalla() {
        // Obtener el tamaño de la pantalla
        Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtener el tamaño del componente
        Dimension componenteTamano = getPreferredSize();

        // Calcular la coordenada x para que el componente esté en el centro de la pantalla
        int x = (pantallaTamano.width - componenteTamano.width) / 2;

        // Calcular la coordenada y par a que el componente esté en el centro de la pantalla
        int y = (pantallaTamano.height - componenteTamano.height) / 2;

        // Establecer la ubicación y el tamaño del componente
        setBounds(x, y, componenteTamano.width, componenteTamano.height);
        setSize(670,490);    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton botonNoIncidencias;
    private javax.swing.JButton botonSiIncidencias;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel confirmacion_o_incidencias;
    private javax.swing.JButton confirmarDevolucion;
    private javax.swing.JTextArea datosVehiculoYCliente;
    private javax.swing.JTextField idReserva;
    private javax.swing.JButton introducirReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numeroPunto;
    private javax.swing.JLabel puntoAC;
    // End of variables declaration//GEN-END:variables

    
}
