package es.uva.eii.ds.empresa7.interfaz.pares_vista_control.attcliente;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 * Vista de incidencias.
 * @author enrmart,fracura,carlgar
 */
public class VistaIncidencias extends javax.swing.JFrame {

    private CtrlVistaIncidencias control;
    /**
     * Creates new form VistaIncidencias
     */
    public VistaIncidencias() {
        this.control = new CtrlVistaIncidencias(this);
        initComponents();
        this.setFont(new Font("Tahoma", Font.BOLD, 14));
        configuraPantalla();
        
        textoCargosExtra.setVisible(false);
        botonIntroducirCargo.setVisible(false);
        cargosExtra.setVisible(false);
        incidenciasIntroducidas.setVisible(false);
        incidenciasIntroducidas.setEditable(false);
        infoInc.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoTipoInc = new javax.swing.JLabel();
        tipoIncidencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoInc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        textoDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionInc = new javax.swing.JTextArea();
        Cancelar = new javax.swing.JButton();
        botonIntroducirIncidencia = new javax.swing.JButton();
        botonFinIncidencias = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        incidenciasIntroducidas = new javax.swing.JTextArea();
        textoCargosExtra = new javax.swing.JLabel();
        cargosExtra = new javax.swing.JTextField();
        botonIntroducirCargo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Incidencias");

        textoTipoInc.setText("Introduzca el tipo de incidencia:");

        infoInc.setEditable(false);
        infoInc.setColumns(20);
        infoInc.setRows(5);
        infoInc.setText("1:Accidente\n2:Averia\n3:Suciedad extrema\n4:Retraso en entrega");
        jScrollPane1.setViewportView(infoInc);

        jLabel2.setText("Informacion sobre tipos de incidencia: ");

        textoDescripcion.setText("Introduzca una breve descripcion: ");

        descripcionInc.setColumns(20);
        descripcionInc.setRows(5);
        jScrollPane2.setViewportView(descripcionInc);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        botonIntroducirIncidencia.setText("Introducir incidencia");
        botonIntroducirIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroducirIncidenciaActionPerformed(evt);
            }
        });

        botonFinIncidencias.setText("Fin de incidencias");
        botonFinIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinIncidenciasActionPerformed(evt);
            }
        });

        incidenciasIntroducidas.setEditable(false);
        incidenciasIntroducidas.setColumns(20);
        incidenciasIntroducidas.setRows(5);
        jScrollPane3.setViewportView(incidenciasIntroducidas);

        textoCargosExtra.setText("¿Existen algun cargo extra?");

        cargosExtra.setText("0");

        botonIntroducirCargo.setText("Introducir cargo");
        botonIntroducirCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroducirCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textoTipoInc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textoDescripcion))
                    .addComponent(botonIntroducirIncidencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cargosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonIntroducirCargo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textoCargosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFinIncidencias)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoTipoInc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(textoDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(textoCargosExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonIntroducirCargo)
                            .addComponent(cargosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIntroducirIncidencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(botonFinIncidencias))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIntroducirIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroducirIncidenciaActionPerformed
        control.procesaEventoAnadirIncidencia();        
    }//GEN-LAST:event_botonIntroducirIncidenciaActionPerformed

    private void botonIntroducirCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroducirCargoActionPerformed
        control.procesaEventoAnadirCargo();
    }//GEN-LAST:event_botonIntroducirCargoActionPerformed

    private void botonFinIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinIncidenciasActionPerformed
        control.finalizaCasoUso();
    }//GEN-LAST:event_botonFinIncidenciasActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        control.procesaEventoVueltaAVistaAtencionCliente();
    }//GEN-LAST:event_CancelarActionPerformed

    
    /**
     * Metodo que devuelve el tipo de incidencia.
     * @return Integer.parseInt(tipoIncidencia.getText()) con el tipo de incidencia
     */
    public String getTipoIncidencia(){
        return  tipoIncidencia.getText();
    }
    
    /**
     * Metodo que devuelve la descripcion de la incidencia.
     * @return descripcionInc.getText() con la descripcion dada
     */
    public String getDescripcionIncidencia(){
        return descripcionInc.getText();
    }
    
    /**
     * Metodo que devuelve el importe asociado a una incidencia
     * @return Double.parseDouble(cargosExtra.getText()) con el importe asociado
     */
    public double getImporte(){
        return Double.parseDouble(cargosExtra.getText());
    }
    
    
    /**
     * Metodo que muestra las opciones para que el usuario introduzca un cargo extra
     */
    public void muestraCargosExtra(){
        botonIntroducirCargo.setVisible(true);
        textoCargosExtra.setVisible(true);
        cargosExtra.setVisible(true);
    }
    
    /**
     * Metodo que muestra las incidencias del listado asociadas a esta Entrega.
     * @param incidencias Arrylist con las incidencias ya introducidas
     */
    public void muestraDatosIncidencias(ArrayList<String> incidencias){
        incidenciasIntroducidas.setVisible(true);
        String textoIncidencias = "";
        for(String i: incidencias){
            textoIncidencias += i;
        }
        incidenciasIntroducidas.setText(textoIncidencias);
        vueltaPasoUno();
    }
    
    private void vueltaPasoUno(){       
        cargosExtra.setText("0");
        descripcionInc.setText("");
        tipoIncidencia.setText("");
        textoCargosExtra.setVisible(false);
        botonIntroducirCargo.setVisible(false);
        cargosExtra.setVisible(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton botonFinIncidencias;
    private javax.swing.JButton botonIntroducirCargo;
    private javax.swing.JButton botonIntroducirIncidencia;
    private javax.swing.JTextField cargosExtra;
    private javax.swing.JTextArea descripcionInc;
    private javax.swing.JTextArea incidenciasIntroducidas;
    private javax.swing.JTextArea infoInc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel textoCargosExtra;
    private javax.swing.JLabel textoDescripcion;
    private javax.swing.JLabel textoTipoInc;
    private javax.swing.JTextField tipoIncidencia;
    // End of variables declaration//GEN-END:variables

    private void configuraPantalla() {
        // Obtener el tamaño de la pantalla
        Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtener el tamaño del componente
        Dimension componenteTamano = getPreferredSize();

        // Calcular la coordenada x para que el componente esté en el centro de la pantalla
        int x = (pantallaTamano.width - componenteTamano.width) / 2;

        // Calcular la coordenada y par a que el componente esté en el centro de la pantalla
        int y = (pantallaTamano.height - componenteTamano.height) / 2;

        // Establecer la ubicación y el tamaño del componente
        setBounds(x, y, componenteTamano.width, componenteTamano.height);
        setSize(670,490);
    }
}
